import java.util.List;
import java.util.Arrays;

public class commonDomains {
	public static final List<String> domains = Arrays.asList(
    "0.0.0.0",
    "255.255.255.255",
		"google.com",
		"youtube.com",
		"facebook.com",
		"wikipedia.org",
		"reddit.com",
		"google.co.in",
		"qq.com",
		"amazon.com",
		"twitter.com",
		"tmall.com",
		"google.co.jp",
		"vk.com",
		"sina.com.cn",
		"360.cn",
		"google.de",
		"google.co.uk",
		"google.com.br",
		"google.fr",
		"google.ru",
		"yandex.ru",
		"twitch.tv",
		"google.it",
		"list.tmall.com",
		"t.co",
		"google.com.hk",
		"google.es",
		"google.ca",
		"yahoo.co.jp",
		"google.com.mx",
		"ok.ru",
		"mail.ru",
		"google.com.tr",
		"google.com.au",
		"whatsapp.com",
		"google.pl",
		"google.co.id",
		"google.com.ar",
		"google.co.th",
		"goo.gl",
		"sm.cn"
		);
}
